[build]
  publish = "."

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/feed.xml"
  [headers.values]
    Content-Type = "application/rss+xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/feeds/all.atom.xml"
  [headers.values]
    Content-Type = "application/atom+xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"

[[headers]]
  for = "/ads.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"

[[redirects]]
  from = "/feed/"
  to = "/feed.xml"
  status = 301

[[redirects]]
  from = "/feed"
  to = "/feed.xml"
  status = 301

[[redirects]]
  from = "/rss.xml"
  to = "/feed.xml"
  status = 301

[[redirects]]
  from = "/rss/"
  to = "/feed.xml"
  status = 301
